<div class="container-fluid">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <div class="well">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#login" aria-controls="login" role="tab" data-toggle="tab">登陆</a></li>
                    <li role="presentation"><a href="#signin" aria-controls="signin" role="tab" data-toggle="tab">注册</a></li>
                    <li role="presentation"><a href="#downapp" aria-controls="downapp" role="tab" data-toggle="tab">下载APP</a></li>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="login">
                        <!-- loginform -->
                        <form id="login-form">
                          <div class="form-group">
                            <input type="input" class="form-control" name="name" placeholder="常用邮箱">
                          </div>
                          <div class="form-group">
                            <input type="password" class="form-control" name="pwd" placeholder="密码">
                          </div>
                          <button type="submit" class="btn btn-default">登陆</button>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="rememberme"> 下次自动登录
                                </label>
                            </div>
                        </form><!-- loginform -->
                    </div>
                    <div role="tabpanel" class="tab-pane" id="signin">
                        <!-- signform -->
                        <form id="sign-form">
                            <div class="form-group">
                                <input type="input" class="form-control" name="name" placeholder="常用邮箱">
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" name="password" placeholder="密码">
                            </div>
                            <button type="submit" class="btn btn-default">注册</button>
                        </form><!-- signform -->
                    </div>
                    <div role="tabpanel" class="tab-pane" id="downapp">
                        开发中....
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<script>
    (function($){

        $("#sign-form").submit(function(){
            $data = $(this).serialize();
            $.post('/index/signin', $data, function($rp){
                if($rp.code == 1){
                    location = $rp.content.location;
                }else{
                    alert($rp.content.msg);
                }
            }, 'json');
            return false;
        });

    })(jQuery);
</script>
